#!/bin/bash

source /opt/Gooby/menus/variables.sh
[[ -d "/var/local/.gtemp" ]] && sudo mv /var/local/.gtemp /var/local/.Gooby

if [ "$EUID" -ne 0 ]; then

	if [ ! -e $CONFIGS/Docker/.env ]; then /opt/Gooby/install/server/server-init.sh; fi

	/opt/Gooby/menus/main.sh

else

	/opt/Gooby/install/server/user-create.sh

fi
