#!/bin/bash

source /opt/GooPlex/menus/variables.sh

if [ "$EUID" -ne 0 ]; then

	if [ ! -e $CONFIGS/Docker/.env ]; then /opt/GooPlex/install/server/server-init.sh; fi

	/opt/GooPlex/menus/main.sh

else

	/opt/GooPlex/install/server/user-create.sh

fi
