#!/bin/bash

sudo mkdir -p $CONFIGS/.config

if [ "$EUID" -ne 0 ]; then

	sudo chown -R $USER:$USER $CONFIGS/.config
	echo "1.1.3" > $CONFIGS/.config/version
	touch $CONFIGS/.config/publicip
	touch $CONFIGS/.config/seturl
	touch $CONFIGS/.config/setemail
	/opt/GooPlex/menus/main.sh

else

	/opt/GooPlex/install/server/user-create.sh

fi
