#!/bin/bash
#
# ------------------------
# Open menu or create user
# ------------------------

if [ $(whoami) = plexuser ]

then

  bash /opt/GooPlex/menus/main.sh

else

  bash /opt/GooPlex/install/createuser.sh

fi
